import React from 'react';
import { ScrollView, StyleSheet, View } from 'react-native';
import { WebView } from 'react-native-webview';
import { theme } from '../theme';

export default function TermsScreen() {
  const htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Terms of Service</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <style>
    body {
      font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      line-height: 1.6;
      padding: 1rem;
      color: ${theme.colors.text};
      background-color: ${theme.colors.background};
    }
    h1, h2 {
      line-height: 1.3;
      color: ${theme.colors.primary};
    }
    footer {
      margin-top: 3rem;
      font-size: 0.9em;
      color: ${theme.colors.textMuted};
      border-top: 1px solid ${theme.colors.tombstone};
      padding-top: 1rem;
    }
  </style>
</head>
<body>

<h1>Terms of Service</h1>

<p><strong>Last updated:</strong> January 7, 2026</p>

<h2>1. Acceptance of Terms</h2>
<p>
By accessing or using this application or website (the "Service"), you agree to be
bound by these Terms of Service. If you do not agree to these terms, you must not
use the Service.
</p>

<h2>2. Provided "As Is"</h2>
<p>
The Service is provided <strong>"as is" and "as available"</strong>, without warranties of any kind,
whether express or implied. This includes, but is not limited to, implied warranties
of merchantability, fitness for a particular purpose, and non-infringement.
</p>

<p>
I make no guarantees regarding the accuracy, reliability, availability, security, or
correctness of the Service or any output it produces.
</p>

<h2>3. No Liability</h2>
<p>
To the maximum extent permitted by applicable law, I shall not be liable for any
damages or losses of any kind, including but not limited to direct, indirect,
incidental, consequential, special, or punitive damages, such as:
</p>

<ul>
  <li>Data loss or corruption</li>
  <li>Financial or business losses</li>
  <li>Service interruptions or unavailability</li>
  <li>Incorrect, incomplete, or misleading output</li>
</ul>

<p>
This applies even if I have been advised of the possibility of such damages.
</p>

<h2>4. Not for Critical or Professional Use</h2>
<p>
The Service is not intended for use in medical, legal, financial, safety-critical, or
other high-risk environments. You acknowledge that any reliance on the Service is
entirely at your own risk.
</p>

<h2>5. Discontinuation and Changes</h2>
<p>
I reserve the right to modify, suspend, or discontinue the Service (in whole or in
part) at any time, with or without notice. I am not responsible for any consequences
resulting from such changes or discontinuation.
</p>

<h2>6. User Responsibility</h2>
<p>
You are solely responsible for your use of the Service and for ensuring that your use
complies with all applicable laws and regulations.
</p>

<h2>7. Governing Law</h2>
<p>
These Terms of Service are governed by and construed in accordance with the laws of
<strong>Belgium</strong>, without regard to its conflict-of-law principles.
</p>

<footer>
  <p>
    <strong>Disclaimer:</strong><br />
    This Terms of Service document was generated by ChatGPT, since I have no money
    to afford a lawyer for sharing my hobby project with the world.
    <strong>Please use this Service completely at your own risk.</strong>
  </p>

  <p>
    © 2026 Arno Deceuninck
  </p>
</footer>

</body>
</html>
  `;

  return (
    <View style={styles.container}>
      <WebView
        originWhitelist={['*']}
        source={{ html: htmlContent }}
        style={styles.webview}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  webview: {
    flex: 1,
  },
});
